### PR TITLE
Add support for SonataAdminBundle 3.x

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks @OskarStark

**Comment by sagikazarmark** [comment]
Whoops, packagist:

```
Importing branch master (dev-master)
Skipped branch master, Invalid package information:
require.sonata-project/admin-bundle : invalid version constraint (Could not parse version constraint  ^3.0: Invalid version string " ^3.0")
```

WTF?

**Comment by OskarStark** [comment]
strange oO

what did you do?

which composer version do you use?

**Comment by sagikazarmark** [comment]
No, this comes from packagist, so either a packagist bug or ?

**Comment by OskarStark** [comment]
@Soullivaneuh do you have an idea?

**Comment by soullivaneuh** [comment]
@sagikazarmark Which version of composer are you using?

Could you try `composer self-update --stable`?

**Comment by sagikazarmark** [comment]
It's not composer. Packagist. Even if I update the package manually on
packagist

Sullivan SENECHAL notifications@github.com ezt írta (2016. június 1.,
szerda):

**Comment by soullivaneuh** [comment]
Oh, you mean on Packagist webhook?

Maybe you should open an issue here: https://github.com/composer/packagist

**Comment by sagikazarmark** [comment]
https://github.com/composer/packagist/issues/682

**Comment by sagikazarmark** [comment]
Ok, fixed. @OskarStark next time try not to use a non-breaking space :stuck_out_tongue_closed_eyes:

**Comment by OskarStark** [comment]
> Ok, fixed. @OskarStark next time try not to use a non-breaking space 😝

wtf, sorry!!

**Pull request merged**
